using UnityEngine;

namespace ButecoDosDevs.NPC
{
    /// <summary>
    /// Drives a non-fighting NPC's SpriteRenderer from 4 static direction sprites
    /// (south/west/east/north, all generated by PixelLab — no flipping needed).
    /// Adds two procedural placeholder animations until real PixelLab animations
    /// exist: a constant subtle "breathing" bob (scale Y 1 -> 1+breathingAmplitude)
    /// and a stronger periodic "activity" bob (e.g. Pedro puffing, Funnie typing)
    /// that fires every activityInterval seconds while activityActive is true.
    /// </summary>
    [RequireComponent(typeof(SpriteRenderer))]
    public class NPCSprite : MonoBehaviour
    {
        private enum FacingDirection
        {
            South,
            West,
            East,
            North
        }

        [Header("Direction sprites (south/west/east/north)")]
        [SerializeField] private Sprite southSprite;
        [SerializeField] private Sprite westSprite;
        [SerializeField] private Sprite eastSprite;
        [SerializeField] private Sprite northSprite;

        [Header("Breathing (always on, subtle)")]
        [SerializeField] private float breathingAmplitude = 0.03f;
        [SerializeField] private float breathingPeriod = 2f;

        [Header("Activity bob (placeholder until PixelLab animations)")]
        [SerializeField] private bool activityActive = true;
        [SerializeField] private float activityInterval = 6f;
        [SerializeField] private float activityBobAmplitude = 0.12f;
        [SerializeField] private float activityBobDuration = 0.35f;

        private SpriteRenderer spriteRenderer;
        private FacingDirection facing = FacingDirection.South;
        private float activityTimer;
        private float activityPulseTimer;
        private Vector3 baseScale;

        private void Awake()
        {
            spriteRenderer = GetComponent<SpriteRenderer>();
            baseScale = transform.localScale;
            activityTimer = activityInterval;
            ApplySprite();
        }

        private void Update()
        {
            float phase = Time.time * (Mathf.PI * 2f / Mathf.Max(breathingPeriod, 0.01f));
            float breathe = 1f + breathingAmplitude * 0.5f * (Mathf.Sin(phase) + 1f);

            float activityScale = 1f;
            if (activityActive)
            {
                activityTimer -= Time.deltaTime;
                if (activityTimer <= 0f)
                {
                    activityTimer = activityInterval;
                    activityPulseTimer = activityBobDuration;
                }

                if (activityPulseTimer > 0f)
                {
                    activityPulseTimer -= Time.deltaTime;
                    float t = Mathf.Clamp01(activityPulseTimer / activityBobDuration);
                    activityScale = 1f + Mathf.Sin(t * Mathf.PI) * activityBobAmplitude;
                }
            }

            float finalYScale = breathe * activityScale;
            transform.localScale = new Vector3(baseScale.x, baseScale.y * finalYScale, baseScale.z);
        }

        /// <summary>
        /// Enables/disables the periodic activity bob (e.g. disabled while talking to the player).
        /// </summary>
        public void SetActivityActive(bool active)
        {
            activityActive = active;
            if (!active)
            {
                activityPulseTimer = 0f;
            }
        }

        /// <summary>
        /// Quantizes the given direction to S/W/E/N and swaps the sprite if it changed.
        /// </summary>
        public void SetFacing(Vector2 direction)
        {
            FacingDirection newFacing = Quantize(direction);
            if (newFacing == facing)
            {
                return;
            }
            facing = newFacing;
            ApplySprite();
        }

        private static FacingDirection Quantize(Vector2 direction)
        {
            if (direction.sqrMagnitude < 0.0001f)
            {
                return FacingDirection.South;
            }

            if (Mathf.Abs(direction.x) >= Mathf.Abs(direction.y))
            {
                return direction.x >= 0f ? FacingDirection.East : FacingDirection.West;
            }

            return direction.y >= 0f ? FacingDirection.North : FacingDirection.South;
        }

        private void ApplySprite()
        {
            if (spriteRenderer == null)
            {
                return;
            }

            switch (facing)
            {
                case FacingDirection.West:
                    spriteRenderer.sprite = westSprite;
                    break;
                case FacingDirection.East:
                    spriteRenderer.sprite = eastSprite;
                    break;
                case FacingDirection.North:
                    spriteRenderer.sprite = northSprite;
                    break;
                default:
                    spriteRenderer.sprite = southSprite;
                    break;
            }
        }
    }
}
